debug: true
db_uri: postgresql://asterisk:proformatique@postgres/asterisk
bus:
  host: rabbitmq
rest_api:
  https:
    listen: 0.0.0.0
    certificate: /data/_common/ssl/agentd/server.crt
    private_key: /data/_common/ssl/agentd/server.key
uuid: fake-uuid
