version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - postgres
    environment:
      TARGETS: "postgres:5432"
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  postgres:
    image: wazopbx/postgres
    ports:
      - "5432"
