debug: true
db_uri: postgresql://asterisk:proformatique@postgres/asterisk
bus:
    host: rabbitmq
consul:
     host: consul
     port: 8500
     token: the_one_ring
agentd:
    host: agentd
    verify_certificate: False
ipbx_connection:
  ipaddress: asterisk
