postgres:
  image: xivo/xivo-postgres
  expose:
    - "5432"
  ports:
    - "15432:5432"
ctid:
  image: xivo/xivo-ctid
  volumes:
    - "./etc/xivo-ctid/conf.d:/etc/xivo-ctid/conf.d"
  expose:
    - "5005"
  links:
    - postgres
    - rabbitmq
    - consul
    - agentd
    - asterisk
    - cti2
  command: xivo-ctid -fd
cti2:
  image: mock-cti
  expose:
    - "6262"
  links:
    - rabbitmq
    - consul
  volumes:
    - "./bin/cti_mock.py:/usr/local/bin/cti_mock.py:ro"
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
consul:
  image: progrium/consul
  expose:
    - "8500"
  ports:
    - "8500:8500"
  volumes:
    - "./etc/consul/config.json:/etc/consul/config.json"
  command: "-client 0.0.0.0 -config-dir /etc/consul"
sync:
  image: n3llyb0y/wait
  links:
    - postgres
    - rabbitmq
    - consul
    - asterisk
    - ctid
    - cti2
    - agentd
  environment:
    PORTS: "5432 5672 8500 5038 6262"
agentd:
  image: xivo/xivo-agentd
  links:
    - postgres
    - rabbitmq
  expose:
    - "9493"
  volumes:
    - "./etc/xivo-agentd/conf.d/config.yml:/etc/xivo-agentd/conf.d/config.yml"
    - "../_common:/data/_common"
  command: xivo-agentd -f
asterisk:
  image: xivo/asterisk
  expose:
    - "5038"
  volumes:
    - "./etc/asterisk/manager.conf:/etc/asterisk/manager.conf"
